#include "platform/windows/operations/magnet_input_isolation_diagnostic.h"
#include <iostream>

namespace i=panebind::test::isolation;
namespace h=panebind::test::handoff;
template<class T> concept HasCursorRoot=requires(T value){value.cursor_root;};
template<class T> concept HasCursor=requires(T value){value.cursor_success;};
static_assert(!HasCursorRoot<i::ProductHandoffAuthorityDiagnostic> && !HasCursor<i::ProductHandoffAuthorityDiagnostic>);
int main(){
    int checks=0;bool all=true;
    const auto check=[&](bool passed,const char* name){++checks;if(!passed){all=false;std::cerr<<"FAIL "<<name<<'\n';}};
    h::HandoffPreflightDiagnostic facts;
    facts.end_observed=facts.winevent_end_observed=facts.own_identity=facts.desktop_ready=facts.source_visible=facts.foreground_matches=true;
    facts.gui_query_succeeded=facts.capture_clear=facts.menu_clear=facts.move_size_clear=facts.gui_in_movesize_clear=true;
    facts.left_down=facts.buttons_modifiers_clear=facts.receiver_healthy=facts.takeover_healthy=facts.dpi_matches=facts.monitor_matches=true;
    facts.actual_positioning_available=facts.actual_visible_available=facts.terminal_positioning_available=facts.terminal_visible_available=facts.terminal_positioning_exact=facts.terminal_visible_exact=true;
    const auto good=i::product_facts(facts);
    check(i::classify_product(good).count==0,"all product facts pass with unavailable/foreign cursor");
    facts.cursor_success=true;facts.cursor_root=999;facts.cursor_root_owned_or_guard=false;
    check(i::product_facts(facts)==good,"cursor/root mutation cannot affect product model");
    check(h::classify(facts).first()==h::Failure::CursorOutsideOwnedInputGuard,"historical C classifier remains unchanged");
    const auto product_failure=[&](auto field,h::Failure failure,const char* label){auto bad=good;bad.*field=false;check(i::classify_product(bad).first()==failure,label);};
    product_failure(&i::ProductHandoffAuthorityDiagnostic::end_observed,h::Failure::MissingNativeEnd,"native END required");
    product_failure(&i::ProductHandoffAuthorityDiagnostic::winevent_end_observed,h::Failure::MissingWinEventEnd,"WinEvent END required");
    product_failure(&i::ProductHandoffAuthorityDiagnostic::own_identity,h::Failure::IdentityChanged,"source identity required");
    product_failure(&i::ProductHandoffAuthorityDiagnostic::desktop_ready,h::Failure::DesktopUnavailable,"desktop required");
    product_failure(&i::ProductHandoffAuthorityDiagnostic::foreground_matches,h::Failure::ForegroundChanged,"foreground required");
    product_failure(&i::ProductHandoffAuthorityDiagnostic::capture_clear,h::Failure::CaptureStillOwned,"capture clear required");
    product_failure(&i::ProductHandoffAuthorityDiagnostic::move_size_clear,h::Failure::MoveSizeStillActive,"movesize clear required");
    product_failure(&i::ProductHandoffAuthorityDiagnostic::terminal_visible_exact,h::Failure::TerminalVisibleMismatch,"visible exact required");
    auto drag=good;drag.native_drag_after_winevent_end=1;check(i::classify_product(drag).first()==h::Failure::NativeDragAfterEnd,"post-END DRAG fails product");
    auto unavailable=good;unavailable.actual_positioning_available=false;unavailable.terminal_positioning_exact=false;check(i::classify_product(unavailable).count==1,"capture unavailability is not a mismatch");
    i::TestInputIsolationDiagnostic isolation;
    isolation.cursor_available=isolation.source_positioning_available=isolation.foreground_matches=true;
    isolation.expected_source=isolation.actual_source={10,20,30,40};isolation.source_positioning={100,100,740,540};isolation.destination={300,550};isolation.root=999;
    check(!isolation.passed()&&i::classify_product(good).count==0,"A foreign cursor blocks test isolation only");
    isolation.shield_needed=isolation.shield_active=isolation.shield_noactivate=isolation.shield_topmost=isolation.shield_visible=isolation.shield_never_activated=true;
    isolation.expected_shield=isolation.actual_shield={11,20,30,40};isolation.shield_positioning={250,540,351,710};isolation.root=11;
    check(isolation.passed(),"B exact post-END shield owns outside point");
    auto invalid=isolation;invalid.source_positioning[2]=invalid.source_positioning[0];check(!invalid.passed(),"degenerate available source rectangle rejected");
    invalid=isolation;invalid.shield_positioning[3]=invalid.shield_positioning[1];check(!invalid.passed(),"degenerate active shield rectangle rejected");
    auto mismatch=isolation; mismatch.actual_shield.nonce=41;check(!mismatch.passed(),"wrong shield nonce");
    mismatch=isolation;mismatch.actual_shield.pid=21;check(!mismatch.passed(),"G wrong shield PID");
    mismatch=isolation;mismatch.actual_shield.tid=31;check(!mismatch.passed(),"G wrong shield TID");
    mismatch=isolation;mismatch.actual_source.pid=21;check(!mismatch.passed(),"G wrong source PID");
    mismatch=isolation;mismatch.actual_source.nonce=0;check(!mismatch.passed(),"G missing source nonce");
    mismatch=isolation;mismatch.foreground_matches=false;check(!mismatch.passed(),"D shield foreground change");
    mismatch=isolation;mismatch.shield_never_activated=false;check(!mismatch.passed(),"D shield activation");
    mismatch=isolation;mismatch.shield_positioning[1]=539;check(!mismatch.passed(),"E shield overlaps current source");
    mismatch=isolation;mismatch.root=999;check(!mismatch.passed(),"F one destination foreign");
    mismatch=isolation;mismatch.destination={300,539};check(!mismatch.passed(),"inside source requires source root");
    mismatch.root=10;check(mismatch.passed(),"inside source correctly resolves source");
    check(i::contains(isolation.shield_positioning,{300,540})&&!i::contains(isolation.source_positioning,{300,540}),"half-open bottom boundary");
    std::array<i::Point,i::planned_point_count> points{};points[0]={300,550};
    for(std::size_t n=1;n<points.size();++n)points[n]={300,550+static_cast<std::int64_t>(n)*6};
    const i::Rect terminal{100,100,740,540};
    const auto plan=i::bottom_shield_plan(terminal,terminal,points);
    check(plan.valid&&plan.needed&&plan.positioning==i::Rect{250,540,351,709},"bounded trajectory plus 50px margin");
    check(plan.top_margin_clipped&&!i::overlaps(plan.positioning,terminal),"margin clipped to never overlap source");
    auto expanded=terminal;expanded[3]=560;const auto dynamic=i::bottom_shield_plan(terminal,expanded,points);
    check(dynamic.valid&&dynamic.positioning[1]==560&&!i::overlaps(dynamic.positioning,expanded),"event-driven dynamic shield nonoverlap");
    expanded[3]=659;const auto final_dynamic=i::position_existing_shield(plan,terminal,expanded);
    check(final_dynamic.valid&&final_dynamic.needed&&final_dynamic.positioning[1]==659&&!i::overlaps(final_dynamic.positioning,expanded),"created shield remains nonoverlapping until Raw UP even if all points now source-owned");
    check(i::matches_planned_cursor({300,550},{300,550}),"planned current exact");
    check(i::matches_planned_cursor({301,549},{300,550}),"existing one-pixel input tolerance");
    check(!i::matches_planned_cursor({302,550},{300,550}),"unexpected current cursor cannot widen shield corridor");
    check(i::contained_rect({0,0,1920,1080},plan.positioning),"planned shield in frozen workarea");
    check(!i::contained_rect({0,0,300,600},plan.positioning),"out-of-workarea shield must fail without clamping");
    auto own_points=points;for(auto& p:own_points)p={300,200};const auto not_needed=i::bottom_shield_plan(terminal,terminal,own_points);
    check(not_needed.valid&&!not_needed.needed,"Move in source does not mechanically create shield");
    auto bad_points=points;bad_points[5]={900,500};check(!i::bottom_shield_plan(terminal,terminal,bad_points).valid,"unsupported side trajectory cannot be bottom shield");
    bad_points=points;bad_points[5]={2147483647LL,550};check(!i::bottom_shield_plan(terminal,terminal,bad_points).valid,"native margin overflow rejected");
    check(!i::source_write_after_gates(40,10,30,0),"C H missing isolation ready");
    check(!i::source_write_after_gates(40,10,30,20),"C shield before END rejected");
    check(!i::source_write_after_gates(35,10,30,35),"H first source write must be strictly after ready");
    check(i::source_write_after_gates(40,10,30,35),"source write after both independent gates");
    check(!i::destroy_after_acceptance(30,40,35),"J shield cannot retire before Raw UP/final acceptance");
    check(i::destroy_after_acceptance(50,40,35),"K destroy after final acceptance and Raw UP");
    if(!all)return 1;std::cout<<"product-input-isolation pure checks="<<checks<<" PASS\n";return 0;
}
