Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
# Pure checks only. Parse definitions; never dot-source the historical replay program.
. (Join-Path $PSScriptRoot 'r1c4b-owned-stability-model.ps1')
$tokens=$null;$errors=$null
$ast=[Management.Automation.Language.Parser]::ParseFile((Join-Path $PSScriptRoot 'replay-r1c4b-fixh-evidence.ps1'),[ref]$tokens,[ref]$errors)
if(@($errors).Count){throw 'corrected replay program does not parse'}
foreach($name in @('Assert-FixHReconstructedFlags','Assert-FixHCorrectedGroup')){
    $nodes=@($ast.FindAll({param($n) $n -is [Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -ceq $name},$true))
    if($nodes.Count -ne 1){throw ('missing unique replay definition '+$name)}
    . ([scriptblock]::Create($nodes[0].Extent.Text))
}
$checks=0
function Check-FixHReplay([bool]$Condition,[string]$Description){if(-not $Condition){throw ('corrected replay fixture: '+$Description)};$script:checks++}
function Reject-FixHReplay([scriptblock]$Action,[string]$Description){
    $rejected=$false
    try{$null=& $Action}catch{$rejected=$true}
    Check-FixHReplay $rejected $Description
}
function Copy-FixHReplay($Value){return $Value|ConvertTo-Json -Depth 18 -Compress|ConvertFrom-Json}
$plan=@(Get-OwnedStabilitySteps)
$fresh=@()
foreach($step in $plan){
    $attempt=New-OwnedStabilityAttempt $step
    $attempt.ChildInvoked=$true;$attempt.PreflightAttempted=$true;$attempt.ProbeInvoked=$true;$attempt.TargetGestureEntered=$true;$attempt.Result='PASS'
    $fresh+=@($attempt)
}
$counts=@(Get-OwnedStabilityCounts $plan $fresh)
Check-FixHReplay ($counts.Count -eq 8) 'fixed eight groups'
for($i=0;$i -lt 8;$i++){
    $n=if($i -lt 4){5}else{20}
    $corrected=$counts[$i]
    # Hand-written expectations, not values generated by the helper under test.
    Check-FixHReplay ($corrected.Planned -eq $n -and $corrected.Attempts -eq $n -and $corrected.PreflightAttempts -eq $n -and $corrected.ProbeInvocations -eq $n -and $corrected.TargetGesturesEntered -eq $n -and $corrected.Passed -eq $n -and $corrected.ProbeInvocationsUnknown -eq 0 -and $corrected.TargetGesturesUnknown -eq 0 -and $corrected.Blocked -eq 0 -and $corrected.Failed -eq 0 -and $corrected.InvalidEvidence -eq 0 -and $corrected.NotRun -eq 0) ("manual expected complete group "+$i)
    $old=Copy-FixHReplay $corrected
    $old.ProbeInvocationsUnknown=$n;$old.TargetGesturesUnknown=$n
    Assert-FixHCorrectedGroup $old $corrected $n
    Check-FixHReplay $true ("only confirmed historical unknown delta "+$i)
    $roundtrip=Copy-FixHReplay $old
    Assert-FixHCorrectedGroup $roundtrip (Copy-FixHReplay $corrected) $n
    Check-FixHReplay $true ("JSON restored historical delta "+$i)
    $bad=Copy-FixHReplay $old;$bad.Passed=($n-1)
    Reject-FixHReplay {Assert-FixHCorrectedGroup $bad $corrected $n} ("unexplained cached pass mismatch "+$i)
    $bad=Copy-FixHReplay $old;$bad.ProbeInvocationsUnknown=($n-1)
    Reject-FixHReplay {Assert-FixHCorrectedGroup $bad $corrected $n} ("wrong old bug signature "+$i)
    $bad=Copy-FixHReplay $corrected;$bad.TargetGesturesUnknown=1
    Reject-FixHReplay {Assert-FixHCorrectedGroup $old $bad $n} ("simultaneous target and unknown "+$i)
}
$known=[pscustomobject]@{ChildInvoked=$true;PreflightAttempted=$true;ProbeInvoked=$true;TargetGestureEntered=$true;Result='PASS';ChildExitCode=0}
Assert-FixHReconstructedFlags $known (Copy-FixHReplay $known) $known
Check-FixHReplay $true 'raw/progress reconstructed booleans agree'
foreach($field in @('ChildInvoked','PreflightAttempted','ProbeInvoked','TargetGestureEntered')){
    foreach($badValue in @($false,'true','UNKNOWN',1,$null)){
        $bad=Copy-FixHReplay $known;$bad.$field=$badValue
        Reject-FixHReplay {Assert-FixHReconstructedFlags $bad $known $known} ("cached "+$field+" cannot relabel actual true as "+[string]$badValue)
        Reject-FixHReplay {Assert-FixHReconstructedFlags $known $bad $known} ("finished "+$field+" cannot relabel actual true as "+[string]$badValue)
    }
    $missing=Copy-FixHReplay $known;$missing.PSObject.Properties.Remove($field)
    Reject-FixHReplay {Assert-FixHReconstructedFlags $missing $known $known} ("missing cached "+$field)
}
$bad=Copy-FixHReplay $known;$bad.Result=$true
Reject-FixHReplay {Assert-FixHReconstructedFlags $bad $known $known} 'boolean PASS cache cannot coerce to string result'
$bad=Copy-FixHReplay $known;$bad.ChildExitCode=$false
Reject-FixHReplay {Assert-FixHReconstructedFlags $bad $known $known} 'boolean exit code cannot coerce to zero'
foreach($token in @('powershell.exe','Start-Process','SendInput','SetCursorPos','GetAsyncKeyState','-Mode normal -RunId')){
    Check-FixHReplay (-not $ast.Extent.Text.Contains($token)) ('historical replay has no input/native child site '+$token)
}
Write-Host ("Fix H corrected replay pure checks={0} PASS; no raw/native/environment/GUI/Git execution" -f $checks)
