Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'r1c4b-input-isolation-replay.ps1')
# Synthetic assessment only: no real UAT read/write, Git, process, GUI or input.
$checks=0
function Check-Replay([bool]$Value,[string]$Reason){if(-not $Value){throw "replay fixture: $Reason"};$script:checks++}
function Copy-ReplayFixture($Value){return ($Value|ConvertTo-Json -Depth 12|ConvertFrom-Json)}
function Reject-Replay([scriptblock]$Action){$rejected=$false;try{$null=& $Action}catch{$rejected=$true};Check-Replay $rejected 'reject malformed historical binding'}
$metadata=[pscustomobject]@{Schema='r1c4b-input-isolation-run/v1';Configuration='Debug';Operation='BottomResize';ExecutedHEAD='a67d3049c1027e8b2b82f8e122041b71ff5043ca';AfterHEAD='a67d3049c1027e8b2b82f8e122041b71ff5043ca';WorktreeDirty=$false;AfterWorktreeDirty=$false;ImplementationUnchanged=$true;ProbeExitCode=0;Result=[pscustomobject]@{Result='INVALID_EVIDENCE'};CurrentContractsVerified=$false;BinarySHA256='43289B87236C08E68EAC2A23BCA1AD9923454DDB21EBF4DE84447083933DEC6D';AfterBinarySHA256='43289B87236C08E68EAC2A23BCA1AD9923454DDB21EBF4DE84447083933DEC6D';LogSHA256='BB1E1F90D58A0B21C5A0B3F65F3A3DDB3994388C96FFE4C6A0F3ED5EF174B76F'}
$verdict=[pscustomobject]@{ContractVerified=$true;SyntheticFixture=$false;Operation='BottomResize';ForegroundContract='verified_global_foreground_v2';HandoffContract='winevent_end_barrier_v1';DiagnosticContract='separated_authority_v1';AuthorityContract='product_gesture_v1';IsolationContract='post_end_shield_v1';Result='PASS';ProductHandoffAuthority='PASS';TestInputIsolation='PASS';PostEndInputShield='PASS';WinEventWitness='PASS';PostEndGeometryStability='PASS';RawBackground='PASS';Cancel='PASS_WITH_TERMINAL_SETTLEMENT';Handoff='PASS';Takeover='PASS';PreReleaseControl='PASS';Architecture='VALID_AT_OWNED_STAGE';ContinuationQuanta=18;NativeDragAfterWinEventEnd=0;UnownedGeometryAfterEnd=0;FullGestureTargets=$true;FinalLeftDown=$false;PendingButton=$false}
$originalMetadata=($metadata|ConvertTo-Json -Depth 12)
$r=Get-IsolationReplayAssessment $metadata $verdict 460
Check-Replay ($r.ReplayResult -ceq 'PASS' -and $r.CorrectedValidatorVerified -and $r.FirstSemanticFailure -ceq 'NONE') 'all full gates required'
Check-Replay (($metadata|ConvertTo-Json -Depth 12) -ceq $originalMetadata) 'original failed metadata never rewritten'
foreach($field in @('Schema','Configuration','Operation','ExecutedHEAD','AfterHEAD','BinarySHA256','AfterBinarySHA256','LogSHA256')){$bad=Copy-ReplayFixture $metadata;$bad.$field='wrong';Reject-Replay {Get-IsolationReplayAssessment $bad $verdict 460}}
foreach($field in @('WorktreeDirty','AfterWorktreeDirty','CurrentContractsVerified')){$bad=Copy-ReplayFixture $metadata;$bad.$field=$true;Reject-Replay {Get-IsolationReplayAssessment $bad $verdict 460}}
$bad=Copy-ReplayFixture $metadata;$bad.Result.Result='PASS';Reject-Replay {Get-IsolationReplayAssessment $bad $verdict 460}
Reject-Replay {Get-IsolationReplayAssessment $metadata $verdict 459}
foreach($field in @('Result','ProductHandoffAuthority','TestInputIsolation','PostEndInputShield','WinEventWitness','PostEndGeometryStability','RawBackground','Cancel','Handoff','Takeover','PreReleaseControl','Architecture')){$bad=Copy-ReplayFixture $verdict;$bad.$field='FAIL';$r=Get-IsolationReplayAssessment $metadata $bad 460;Check-Replay ($r.ReplayResult -ceq 'FAIL' -and -not $r.CorrectedValidatorVerified -and $r.FirstSemanticFailure -ceq ($field+'=FAIL')) "full replay rejects $field"}
foreach($field in @('ContractVerified','ForegroundContract','HandoffContract','DiagnosticContract','AuthorityContract','IsolationContract','Operation')){$bad=Copy-ReplayFixture $verdict;if($field -eq 'ContractVerified'){$bad.$field=$false}else{$bad.$field='wrong'};Reject-Replay {Get-IsolationReplayAssessment $metadata $bad 460}}
$bad=Copy-ReplayFixture $verdict;$bad.SyntheticFixture=$true;Reject-Replay {Get-IsolationReplayAssessment $metadata $bad 460}
foreach($fault in @('quanta','drag','unowned','anchor','left','pending')){$bad=Copy-ReplayFixture $verdict;switch($fault){'quanta'{$bad.ContinuationQuanta=17};'drag'{$bad.NativeDragAfterWinEventEnd=1};'unowned'{$bad.UnownedGeometryAfterEnd=1};'anchor'{$bad.FullGestureTargets=$false};'left'{$bad.FinalLeftDown=$true};'pending'{$bad.PendingButton=$true}};$r=Get-IsolationReplayAssessment $metadata $bad 460;Check-Replay ($r.ReplayResult -ceq 'FAIL') "terminal replay rejects $fault"}
foreach($exception in @([OverflowException]::new('overflow'),[IO.InvalidDataException]::new('missing/type'),[Exception]::new('unexpected crash'),[InvalidOperationException]::new('unexpected operation'))){$r=Get-IsolationReplayExceptionAssessment $exception;Check-Replay ($r.ReplayResult -ceq 'INVALID_EVIDENCE' -and -not $r.CorrectedValidatorVerified -and $r.FirstSemanticFailure -ceq 'NONE') 'exceptions stop as invalid evidence'}
$r=Get-IsolationReplayExceptionAssessment ([InvalidOperationException]::new('owned input isolation: semantic assertion'));Check-Replay ($r.ReplayResult -ceq 'FAIL' -and $r.FirstSemanticFailure -ceq 'owned input isolation: semantic assertion') 'semantic assertion stops as FAIL'
$tokens=$null;$errors=$null;$ast=[Management.Automation.Language.Parser]::ParseFile((Join-Path $PSScriptRoot 'revalidate-r1c4b-input-isolation.ps1'),[ref]$tokens,[ref]$errors)
Check-Replay (@($errors).Count -eq 0) 'replay program parses'
$commands=@($ast.FindAll({param($n)$n -is [Management.Automation.Language.CommandAst]},$true))
Check-Replay (@($commands|Where-Object {$_.GetCommandName() -in @('powershell.exe','Start-Process','Set-Content','Add-Content') -or $_.InvocationOperator -eq [Management.Automation.Language.TokenKind]::Ampersand}).Count -eq 0) 'no CLI/probe invocation or replacing writes'
Check-Replay ($ast.Extent.Text.Contains('[IO.FileMode]::CreateNew') -and $ast.Extent.Text.Contains('$afterLog -ceq $logHash -and $afterMetadata -ceq $metadataHash')) 'artifact creation cannot overwrite and preserves both original hashes'
Check-Replay ($ast.Extent.Text.Contains('$afterSource -ceq $sourceHash -and $afterBinary -ceq $binaryHash') -and $ast.Extent.Text.Contains('AfterBinarySHA256=$afterBinary;AfterRuntimeSourceSHA256=$afterSource')) 'runtime source/binary checked before and after replay without launching it'
Write-Host "input-isolation-replay synthetic_only=true checks=$checks PASS; no GUI/input/original evidence writes"
